version: 2.1

jobs:
  hello-world:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Hello world
          command: echo "Hello World"

workflows:
  version: 2.1

  build:
    jobs:
      - hello-world
